//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace fitness.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class fitnessandlifestyle : DbContext
    {
        public fitnessandlifestyle()
            : base("name=fitnessandlifestyle")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AspNetRole> AspNetRoles { get; set; }
        public virtual DbSet<AspNetUserClaim> AspNetUserClaims { get; set; }
        public virtual DbSet<AspNetUserLogin> AspNetUserLogins { get; set; }
        public virtual DbSet<AspNetUser> AspNetUsers { get; set; }
        public virtual DbSet<Daily_Diet> Daily_Diet { get; set; }
        public virtual DbSet<DayPerWeek> DayPerWeeks { get; set; }
        public virtual DbSet<Diet_DayPerWeek> Diet_DayPerWeek { get; set; }
        public virtual DbSet<DietPlan> DietPlans { get; set; }
        public virtual DbSet<Exercise> Exercises { get; set; }
        public virtual DbSet<Goal> Goals { get; set; }
        public virtual DbSet<GoalProgess> GoalProgesses { get; set; }
        public virtual DbSet<Order> Orders { get; set; }
        public virtual DbSet<Resource> Resources { get; set; }
        public virtual DbSet<WorkOut> WorkOuts { get; set; }
        public virtual DbSet<Schedule> Schedules { get; set; }
        public virtual DbSet<C__MigrationHistory> C__MigrationHistory { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
    }
}
