//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace fitness.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GoalProgess
    {
        public int Id { get; set; }
        public Nullable<double> CurrentWeight { get; set; }
        public Nullable<double> CurrentHeight { get; set; }
        public Nullable<int> GoalId { get; set; }
        public Nullable<System.DateTime> timestamp { get; set; }
    
        public virtual Goal Goal { get; set; }
    }
}
