//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace fitness.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        public int Id { get; set; }
        public string UserId { get; set; }
        public Nullable<int> WorkoutId { get; set; }
        public Nullable<int> DietplanId { get; set; }
        public Nullable<System.DateTime> timestamp { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
        public virtual DietPlan DietPlan { get; set; }
        public virtual WorkOut WorkOut { get; set; }
    }
}
