//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace fitness.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Schedule
    {
        public int Id { get; set; }
        public Nullable<int> DayPerWeekId { get; set; }
        public Nullable<int> WorkOutId { get; set; }
        public Nullable<int> Status { get; set; }
        public Nullable<int> reps { get; set; }
        public Nullable<int> sets { get; set; }
        public Nullable<int> ExId { get; set; }
    
        public virtual DayPerWeek DayPerWeek { get; set; }
        public virtual Exercise Exercise { get; set; }
        public virtual WorkOut WorkOut { get; set; }
    }
}
