//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace fitness.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Daily_Diet
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Content { get; set; }
        public string Link { get; set; }
        public Nullable<int> DDId { get; set; }
    
        public virtual Diet_DayPerWeek Diet_DayPerWeek { get; set; }
    }
}
