//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace fitness.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Diet_DayPerWeek
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Diet_DayPerWeek()
        {
            this.Daily_Diet = new HashSet<Daily_Diet>();
        }
    
        public int Id { get; set; }
        public Nullable<int> DayPerWeekId { get; set; }
        public Nullable<int> DietID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Daily_Diet> Daily_Diet { get; set; }
        public virtual DayPerWeek DayPerWeek { get; set; }
        public virtual DietPlan DietPlan { get; set; }
    }
}
