//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace fitness.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Exercise
    {
        public int Id { get; set; }
        public string Title { get; set; }
        public string Content { get; set; }
        public string Link { get; set; }
        public int exerciseReps { get; set; }
        public int exersiceSets { get; set; }
        public Nullable<int> WorkOutId { get; set; }
    
        public virtual WorkOut WorkOut { get; set; }
    }
}
