//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace fitness.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Goal
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Goal()
        {
            this.GoalProgresses = new HashSet<GoalProgress>();
        }
    
        public int Id { get; set; }
        public double weightDesired { get; set; }
        public Nullable<bool> StatusGoal { get; set; }
        public int UserId { get; set; }
        public int Category { get; set; }
    
        public virtual ProfileUser ProfileUser { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GoalProgress> GoalProgresses { get; set; }
    }
}
