//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace fitness.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        public int Id { get; set; }
        public int UserId { get; set; }
        public Nullable<int> WorkOutId { get; set; }
        public Nullable<int> DietPlanId { get; set; }
    
        public virtual DietPlan DietPlan { get; set; }
        public virtual ProfileUser ProfileUser { get; set; }
        public virtual WorkOut WorkOut { get; set; }
    }
}
