//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace fitness.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Workout_DayPerWeek
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Workout_DayPerWeek()
        {
            this.Exercises = new HashSet<Exercise>();
        }
    
        public int Id { get; set; }
        public Nullable<int> DayPerWeekId { get; set; }
        public Nullable<int> WorkOutId { get; set; }
        public Nullable<int> Status { get; set; }
    
        public virtual DayPerWeek DayPerWeek { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Exercise> Exercises { get; set; }
        public virtual WorkOut WorkOut { get; set; }
    }
}
